# coding: utf-8

"""
    Lists

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from hubspot.crm.lists.configuration import Configuration


class PublicRelativeRangedTimestampRefineBy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"upper_bound_offset": "PublicTimeOffset", "range_type": "str", "lower_bound_offset": "PublicTimeOffset", "type": "str"}

    attribute_map = {"upper_bound_offset": "upperBoundOffset", "range_type": "rangeType", "lower_bound_offset": "lowerBoundOffset", "type": "type"}

    def __init__(self, upper_bound_offset=None, range_type=None, lower_bound_offset=None, type="RELATIVE_RANGED", local_vars_configuration=None):  # noqa: E501
        """PublicRelativeRangedTimestampRefineBy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._upper_bound_offset = None
        self._range_type = None
        self._lower_bound_offset = None
        self._type = None
        self.discriminator = None

        self.upper_bound_offset = upper_bound_offset
        self.range_type = range_type
        self.lower_bound_offset = lower_bound_offset
        self.type = type

    @property
    def upper_bound_offset(self):
        """Gets the upper_bound_offset of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501


        :return: The upper_bound_offset of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :rtype: PublicTimeOffset
        """
        return self._upper_bound_offset

    @upper_bound_offset.setter
    def upper_bound_offset(self, upper_bound_offset):
        """Sets the upper_bound_offset of this PublicRelativeRangedTimestampRefineBy.


        :param upper_bound_offset: The upper_bound_offset of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :type upper_bound_offset: PublicTimeOffset
        """
        if self.local_vars_configuration.client_side_validation and upper_bound_offset is None:  # noqa: E501
            raise ValueError("Invalid value for `upper_bound_offset`, must not be `None`")  # noqa: E501

        self._upper_bound_offset = upper_bound_offset

    @property
    def range_type(self):
        """Gets the range_type of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501


        :return: The range_type of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :rtype: str
        """
        return self._range_type

    @range_type.setter
    def range_type(self, range_type):
        """Sets the range_type of this PublicRelativeRangedTimestampRefineBy.


        :param range_type: The range_type of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :type range_type: str
        """
        if self.local_vars_configuration.client_side_validation and range_type is None:  # noqa: E501
            raise ValueError("Invalid value for `range_type`, must not be `None`")  # noqa: E501

        self._range_type = range_type

    @property
    def lower_bound_offset(self):
        """Gets the lower_bound_offset of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501


        :return: The lower_bound_offset of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :rtype: PublicTimeOffset
        """
        return self._lower_bound_offset

    @lower_bound_offset.setter
    def lower_bound_offset(self, lower_bound_offset):
        """Sets the lower_bound_offset of this PublicRelativeRangedTimestampRefineBy.


        :param lower_bound_offset: The lower_bound_offset of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :type lower_bound_offset: PublicTimeOffset
        """
        if self.local_vars_configuration.client_side_validation and lower_bound_offset is None:  # noqa: E501
            raise ValueError("Invalid value for `lower_bound_offset`, must not be `None`")  # noqa: E501

        self._lower_bound_offset = lower_bound_offset

    @property
    def type(self):
        """Gets the type of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501


        :return: The type of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PublicRelativeRangedTimestampRefineBy.


        :param type: The type of this PublicRelativeRangedTimestampRefineBy.  # noqa: E501
        :type type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["RELATIVE_RANGED"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and type not in allowed_values:  # noqa: E501
            raise ValueError("Invalid value for `type` ({0}), must be one of {1}".format(type, allowed_values))  # noqa: E501

        self._type = type

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item: (item[0], convert(item[1])), value.items()))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublicRelativeRangedTimestampRefineBy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PublicRelativeRangedTimestampRefineBy):
            return True

        return self.to_dict() != other.to_dict()
