# coding: utf-8

# flake8: noqa

"""
    Feedback Submissions

    CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.  ## Supported Object Types  This API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by exploring the [CRM Object Properties API](https://developers.hubspot.com/docs/methods/crm-properties/crm-properties-overview).  |Object Type |Properties returned by default | |--|--| | `companies` | `name`, `domain` | | `contacts` | `firstname`, `lastname`, `email` | | `deals` | `dealname`, `amount`, `closedate`, `pipeline`, `dealstage` | | `products` | `name`, `description`, `price` | | `tickets` | `content`, `hs_pipeline`, `hs_pipeline_stage`, `hs_ticket_category`, `hs_ticket_priority`, `subject` |  Find a list of all properties for an object type using the [CRM Object Properties](https://developers.hubspot.com/docs/methods/crm-properties/get-properties) API. e.g. `GET https://api.hubapi.com/properties/v2/companies/properties`. Change the properties returned in the response using the `properties` array in the request body.  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from hubspot.crm.objects.feedback_submissions.api.basic_api import BasicApi
from hubspot.crm.objects.feedback_submissions.api.batch_api import BatchApi
from hubspot.crm.objects.feedback_submissions.api.search_api import SearchApi

# import ApiClient
from hubspot.crm.objects.feedback_submissions.api_client import ApiClient
from hubspot.crm.objects.feedback_submissions.configuration import Configuration
from hubspot.crm.objects.feedback_submissions.exceptions import OpenApiException
from hubspot.crm.objects.feedback_submissions.exceptions import ApiTypeError
from hubspot.crm.objects.feedback_submissions.exceptions import ApiValueError
from hubspot.crm.objects.feedback_submissions.exceptions import ApiKeyError
from hubspot.crm.objects.feedback_submissions.exceptions import ApiAttributeError
from hubspot.crm.objects.feedback_submissions.exceptions import ApiException

# import models into sdk package
from hubspot.crm.objects.feedback_submissions.models.associated_id import AssociatedId
from hubspot.crm.objects.feedback_submissions.models.batch_read_input_simple_public_object_id import BatchReadInputSimplePublicObjectId
from hubspot.crm.objects.feedback_submissions.models.batch_response_simple_public_object import BatchResponseSimplePublicObject
from hubspot.crm.objects.feedback_submissions.models.collection_response_associated_id import CollectionResponseAssociatedId
from hubspot.crm.objects.feedback_submissions.models.collection_response_simple_public_object_with_associations import CollectionResponseSimplePublicObjectWithAssociations
from hubspot.crm.objects.feedback_submissions.models.collection_response_with_total_simple_public_object import CollectionResponseWithTotalSimplePublicObject
from hubspot.crm.objects.feedback_submissions.models.error import Error
from hubspot.crm.objects.feedback_submissions.models.error_detail import ErrorDetail
from hubspot.crm.objects.feedback_submissions.models.filter import Filter
from hubspot.crm.objects.feedback_submissions.models.filter_group import FilterGroup
from hubspot.crm.objects.feedback_submissions.models.next_page import NextPage
from hubspot.crm.objects.feedback_submissions.models.paging import Paging
from hubspot.crm.objects.feedback_submissions.models.previous_page import PreviousPage
from hubspot.crm.objects.feedback_submissions.models.public_object_search_request import PublicObjectSearchRequest
from hubspot.crm.objects.feedback_submissions.models.simple_public_object import SimplePublicObject
from hubspot.crm.objects.feedback_submissions.models.simple_public_object_id import SimplePublicObjectId
from hubspot.crm.objects.feedback_submissions.models.simple_public_object_with_associations import SimplePublicObjectWithAssociations
from hubspot.crm.objects.feedback_submissions.models.standard_error import StandardError
from hubspot.crm.objects.feedback_submissions.models.value_with_timestamp import ValueWithTimestamp
