name: lint_python
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B105,B107 .
      - run: black --check . || true
      - run: codespell --ignore-words-list="fo,nd,querys,seh,te" || true  # --skip="*.css,*.js,*.lock"
      - run: flake8 . --count --ignore=B006,C409,C417,E302,F401,W291,W292,W293,W605,YTT202
                      --max-complexity=21 --max-line-length=208 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=21 --max-line-length=208
                      --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install --editable .
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: pytest tests
      - run: pytest --doctest-modules . || pytest . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
